const initialConfigJSON = require(`./config.json`);
const path = require(`path`);
const configurator = require(`../index`);

const TEST_PREFIX = `TEST_PREFIX`;

process.env[`${TEST_PREFIX}.HAS_CORRESPONDING_ENV_VAR`] = `Overridden`;
process.env[`${TEST_PREFIX}.DEEP_CONFIGURATION.FIRST_DEEP_TEST_ENV_VAR`] = `HelloWorld`;
process.env[`${TEST_PREFIX}.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.SECOND_DEEP_TEST_ENV_VAR`] = `777`;
process.env[`${TEST_PREFIX}.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.DEEPEST_CONFIGURATION.THIRD_DEEP_TEST_ENV_VAR`] = `yes`;

const config = configurator(path.join(__dirname, `./config.json`), TEST_PREFIX);

console.log(`${config.NO_CORRESPONDING_ENV_VAR} should be ${initialConfigJSON.NO_CORRESPONDING_ENV_VAR}`);
console.log(`${config.HAS_CORRESPONDING_ENV_VAR} should be ${process.env[`${TEST_PREFIX}.HAS_CORRESPONDING_ENV_VAR`]}`);
console.log(`${config.DEEP_CONFIGURATION.FIRST_DEEP_TEST} should be ${initialConfigJSON.DEEP_CONFIGURATION.FIRST_DEEP_TEST}`);
console.log(`${config.DEEP_CONFIGURATION.FIRST_DEEP_TEST_ENV_VAR} should be ${process.env[`${TEST_PREFIX}.DEEP_CONFIGURATION.FIRST_DEEP_TEST_ENV_VAR`]}`);
console.log(`${config.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.SECOND_DEEP_TEST} should be ${initialConfigJSON.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.SECOND_DEEP_TEST}`);
console.log(`${config.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.SECOND_DEEP_TEST_ENV_VAR} should be ${process.env[`${TEST_PREFIX}.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.SECOND_DEEP_TEST_ENV_VAR`]}`);
console.log(`${config.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.DEEPEST_CONFIGURATION.THIRD_DEEP_TEST} should be ${initialConfigJSON.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.DEEPEST_CONFIGURATION.THIRD_DEEP_TEST}`);
console.log(`${config.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.DEEPEST_CONFIGURATION.THIRD_DEEP_TEST_ENV_VAR} should be ${process.env[`${TEST_PREFIX}.DEEP_CONFIGURATION.DEEPER_CONFIGURATION.DEEPEST_CONFIGURATION.THIRD_DEEP_TEST_ENV_VAR`]}`);